[project]
name = "minimal-alpha-zero"
version = "0.1.0"
description = "Minimal AlphaZero"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flax>=0.12.2",
    "joblib>=1.5.3",
    "pytest>=9.0.2",
]
